The redis config file must be the first parameter
groundhog2k/helm-charts pull request #455
Opened 2021-06-04 12:53 UTC by bbkz

otherwise the redis-server binary will crash with

> Bad directive or wrong number of arguments

2021-06-04 14:34 UTC, groundhog2k requested changes
Thanks for finding and fixing this! 
Please apply the fix also to the sentinel-container.

Update the Chart version in Chart.yaml and README to 0.4.6.
(Thank you!)

2021-06-04 14:34 UTC, groundhog2k commented on charts/redis/templates/statefulset.yaml
> +            - /data/conf/redis.conf
Please apply the same fix for the redis-sentinel container (around line 195)

2021-06-05 08:15 UTC, groundhog2k commented
Closes #456

2021-06-07 08:18 UTC, bbkz commented
Hi,

i added the change for sentinel and updated the chart version.

Yours,
bbk

2021-06-07 09:39 UTC, groundhog2k approved these changes

2021-06-07 09:40 UTC, merged